### ISSUE TITLE
Exporting isosurface causes segmentation fault

### ISSUE THREAD

**Issue by BartBruininks** [nzfeng/signed-heat-3d#3] opened 2024-09-10 10:31 UTC
I ran the anaylsis using a `grid` with `tCoef` of `1` and `hCoef` of `1.5` on the added mesh. The mesh contains two holes in its surface which I attempt to reconstruct (like was shown in the manuscript for the bunny).

When I try to export the isosurface at 0.01 distance, I get a segmentation error. Here is all the output polyscope throws to the terminal:
```
[polyscope] Backend: openGL3_glfw -- Loaded openGL version: 4.6 (Core Profile) Mesa 21.2.6
Segmentation fault (core dumped)
```
Input mesh:
![broken_bilayer](https://github.com/user-attachments/assets/99d339cc-dc63-493f-a779-a143313405f8)
[broken-bilayer_low-poly.ply.gz](https://github.com/user-attachments/files/16943366/broken-bilayer_low-poly.ply.gz)

**Comment by nzfeng** [comment] 2024-09-10 17:33
Caused by out-of-bounds access from not sizing std::vector correctly, fixed in [a698114](https://github.com/nzfeng/signed-heat-3d/commit/a698114c4e2f8e8d11758c8174a0acaa421e3081). Thanks for catching!

**Closed by nzfeng** 2024-09-10 17:33 UTC
